version: "3"
services:
    neo4j:
        image: neo4j:3.4.1
        deploy:
            replicas: 1
        ports:
            - "7678:7474"
            - "7691:7687"
        networks:
            - mytaxsysnetdev
        environment:
            NEO4J_AUTH: "neo4j/wallaby"
    restagraph:
        image: equill/mytaxsys:0.1.4
        deploy:
            replicas: 1
        ports:
            - "4956:4949"
        networks:
            - mytaxsysnetdev
        environment:
            LISTEN_ADDR: "0.0.0.0"
            LISTEN_PORT: 4949
            NEO4J_HOSTNAME: "neo4j"
            NEO4J_PORT: 7474
            NEO4J_USER: "neo4j"
            NEO4J_PASSWORD: "wallaby"
networks:
    mytaxsysnetdev:
